name: "Network"
version: "1.0"

channels:
  docschannel:
    orderers:
      - orderer.astu.com
    peers:
      astu-admin-peer1.astu.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      astu-service-peer1.astu.com:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false

organizations:
  Astu:
    mspid: AstuMSP
    peers:
      - astu-admin-peer1.astu.com
    certificateAuthorities:
      - ca.caserver.com
    adminPrivateKey:
      path: ../crypto/crypto-config/peerOrganizations/astu.com/users/Admin@astu.com/msp/keystore/e0e1ec4237fd02daae6699f53b5d485615bef5b57ec519dc58a7241c08f07ed1_sk
    signedCert:
      path: ../crypto/crypto-config/peerOrganizations/astu.com/users/Admin@astu.com/msp/signcerts/Admin@astu.com-cert.pem

  Service:
    mspid: ServiceMSP
    peers:
      - astu-service-peer1.astu.com
    certificateAuthorities:
      - ca.caserver.com
    adminPrivateKey:
      path: ../crypto/crypto-config/peerOrganizations/astu-service.com/users/Admin@astu-service.com/msp/keystore/05beac9849f610ad5cc8997e5f45343ca918de78398988def3f288b60d8ee27c_sk
    signedCert:
      path: ../crypto/crypto-config/peerOrganizations/astu-service.com/users/Admin@astu-service.com/msp/signcerts/Admin@astu-service.com-cert.pem

orderers:
  orderer.astu.com:
    url: grpc://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.astu.com
      grpc-max-send-message-length: 15
    # tlsCACerts:
    #   path: ../crypto/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tlscacerts/example.com-cert.pem

peers:
  astu-admin-peer1.astu.com:
    url: grpc://localhost:7051
    grpcOptions:
      ssl-target-name-override: astu-admin-peer1.astu.com
      grpc.keepalive_time_ms: 600000
    # tlsCACerts:
    #   path: ../crypto/crypto-config/peerOrganizations/astu.com/peers/peer0.astu.com/tlscacerts/astu.com-cert.pem

  astu-service-peer1.astu.com:
    url: grpc://localhost:8051
    grpcOptions:
      ssl-target-name-override: astu-service-peer1.astu.com
    # tlsCACerts:
    #   path: ../crypto/crypto-config/peerOrganizations/astu-service.com/peers/peer0.astu-service.com/tlscacerts/astu-service.com-cert.pem

certificateAuthorities:
  ca.caserver.com:
    url: http://localhost:7054
    httpOptions:
      verify: false
    # tlsCACerts:
    #   path: ../crypto/crypto-config/peerOrganizations/astu.com/ca/cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: caserver

