name: Network
version: '1.0'
channels:
  docschannel:
    orderers:
      - orderer.astu.com
    peers:
      astu-admin-peer1.astu.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      astu-service-peer1.astu.com:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false
organizations:
  Astu:
    mspid: AstuMSP
    peers:
      - astu-admin-peer1.astu.com
    certificateAuthorities:
      - ca.caserver.com
    adminPrivateKey:
      path: >-
        /vagrant/network/bin/../crypto/crypto-config/peerOrganizations/astu.com/users/Admin@astu.com/msp/keystore/2de85d725ae81a8babfb20be0574363e13476ebbd26ebbe46c3a2f5c3d4edad1_sk
    signedCert:
      path: >-
        /vagrant/network/bin/../crypto/crypto-config/peerOrganizations/astu.com/users/Admin@astu.com/msp/signcerts/Admin@astu.com-cert.pem
  Service:
    mspid: ServiceMSP
    peers:
      - astu-service-peer1.astu.com
    certificateAuthorities:
      - ca.caserver.com
    adminPrivateKey:
      path: >-
        /vagrant/network/bin/../crypto/crypto-config/peerOrganizations/astu-service.com/users/Admin@astu-service.com/msp/keystore/53c3769f14a231c155fa4b1872bc768be05c0560e77c7d41c6d27b6e169ac0a7_sk
    signedCert:
      path: >-
        /vagrant/network/bin/../crypto/crypto-config/peerOrganizations/astu-service.com/users/Admin@astu-service.com/msp/signcerts/Admin@astu-service.com-cert.pem
orderers:
  orderer.astu.com:
    url: 'grpc://localhost:7050'
    grpcOptions:
      ssl-target-name-override: orderer.astu.com
      grpc-max-send-message-length: 15
peers:
  astu-admin-peer1.astu.com:
    url: 'grpc://localhost:7051'
    grpcOptions:
      ssl-target-name-override: astu-admin-peer1.astu.com
      grpc.keepalive_time_ms: 600000
  astu-service-peer1.astu.com:
    url: 'grpc://localhost:8051'
    grpcOptions:
      ssl-target-name-override: astu-service-peer1.astu.com
certificateAuthorities:
  ca.caserver.com:
    url: 'http://localhost:7054'
    httpOptions:
      verify: false
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: caserver
