# Defines three organizations
#  - Orderer organization
#  - Org1  = Single peer organization
#    Uses the "Specs" to declare the peers instead of Template
#  - Org2  = Another peer organization
# SOLUTION to the exercise

##### Orderer for astu
OrdererOrgs:
  - Name: Orderer
    Domain: astu.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      
#### Peers for astu
PeerOrgs:
  # Peer configuration for ACME
  - Name: Astu
    #Domain: astu.com
    Domain: astu.com
    EnableNodeOUs: true
    Specs:
      - Hostname: astu-peer1
      #- Hostname: astu-peer1
        CommonName: astu-peer1
    Users:
      Count: 1

  # Peer configuration for Astu-Service
  - Name: Astu-Service
    #Domain: astu-service.com
    Domain: astu-service.com
    EnableNodeOUs: true
    Specs:
      - Hostname: astu-service-peer1
      #- Hostname: astu-service-peer1
        CommonName: astu-service-peer1
    Users:
      Count: 1



      