# Docker compose for multi-org-ca-1
#DEV_MODE_DEV
version: '2'

networks:
  docs:

services:
  

  # Astu peer1
  astu-peer1.couchdb:
    container_name: astu-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "5984:5984"
    networks:
      - docs

  astu-admin-peer1.astu.com:
    container_name: astu-admin-peer1.astu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=astu-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - astu-peer1.couchdb

  # Astu-Service peer1
  astu-service-peer1.couchdb:
    container_name: astu-service-peer1.couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - docs

  astu-service-peer1.astu.com:
    container_name: astu-service-peer1.astu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=astu-service-peer1.couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - astu-service-peer1.couchdb
    