# Docker compose for multi-org-ca-1
#DEV_MODE_DEV
version: '2'

networks:
  docs:

services:
  

  # Astu peer1
  astu-admin-peer1.astu.com:
    container_name: astu-admin-peer1.astu.com
    
    command: peer node start --peer-chaincodedev=true
    

  # Astu-Service peer1
  astu-service-peer1.astu.com:
    container_name: astu-service-peer1.astu.com
    
    command: peer node start --peer-chaincodedev=true
    