version: '2'

networks:
  docs:

services:
  # Orderer
  orderer.astu.com:
    container_name: orderer.astu.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=orderer.astu.com
      - ORDERER_GENERAL_GENESISMETHOD=file
      # - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/genesis/docs-genesis.block
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/genesis/docs-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
      - ORDERER_FILELEDGER_LOCATION=/var/ledger
    working_dir: $HOME
    command: orderer
    volumes:
    # Folder with genesis block
    - ${PWD}/config/orderer:/var/hyperledger/genesis
    # Map the folder with MSP for orderer
    - ${PWD}/client/orderer/orderer//msp:/var/hyperledger/msp
    # Map the current folder to cfg
    - ${PWD}/config/orderer:/var/hyperledger/config
    - ${HOME}/ledgers/ca/orderer.astu.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - docs

  # Astu peer1
  astu-admin-peer1.astu.com:
    container_name: astu-admin-peer1.astu.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=INFO

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_docs

      - CORE_PEER_ID=astu-admin-peer1.astu.com
      # - CORE_PEER_LISTENADDRESS=astu-service-peer1.astu.com:7051
      - CORE_PEER_ADDRESS=astu-admin-peer1.astu.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=astu-admin-peer1.astu.com:7051
      # - CORE_PEER_ADDRESS=0.0.0.0:7051
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:7051

      - CORE_PEER_LOCALMSPID=AstuMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/client/astu/peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/ca/astu-admin-peer1.astu.com/:/var/ledger
    depends_on: 
      - orderer.astu.com
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    networks:
      - docs

  # Astu-Service peer1
  astu-service-peer1.astu.com:
    container_name: astu-service-peer1.astu.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=INFO

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_docs

      - CORE_PEER_ID=astu-service-peer1.astu.com
      - CORE_PEER_ADDRESS=astu-service-peer1.astu.com:8051
      # - CORE_PEER_LISTENADDRESS=astu-service-peer1.astu.com:8051
      - CORE_PEER_LISTENADDRESS=astu-service-peer1.astu.com:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=astu-service-peer1.astu.com:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=astu-service-peer1.astu.com:8051
      - CORE_PEER_LOCALMSPID=Astu-ServiceMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/client/astu-service/peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/ca/astu-service-peer1.astu.com:/var/ledger
    depends_on: 
      - orderer.astu.com
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    networks:
      - docs

  